### ISSUE TITLE
Improve remove_dims_of

### ISSUE THREAD

**Issue by blegouix** [CExA-project/ddc#190]
support:
`remove_dims_of<DimsToRemove...>(dom)`
in addition to:
`remove_dims_of(dom, dom_to_remove)`

(and make the change in gysela advection)

**Comment by tpadioleau** [comment]
Yes I think we get closer to something user-friendly.

I am also considering a member function like the current `DiscreteDomain::remove` that returns a new `DiscreteDomain` with the same dimensions. What do you think of `DiscreteDomain DiscreteDomain::remove_dims_from(DiscreteDomain<DimsToRemove...> const& x)` that would return a new `DiscreteDomain` without the dimensions found in `x` ?

An other possibility would be to introduce a template class `dims<Dims...>` that would be an empty object representing the dimensions (not intervals but complete dimensions). You would use it like `remove_dims_of(dom, dims(DimsToRemove()...))`.
