### ISSUE TITLE
Overload algorithms to take a string as a first parameter

### ISSUE THREAD

**Issue by tpadioleau** [CExA-project/ddc#297]
The idea is to follow Kokkos convention regarding the standard algorithms.

**Comment by tpadioleau** [comment]
This will be helpful for users of Kokkos tools.

**Comment by tpadioleau** [comment]
- [ ] `parallel_for_each`
- [ ] `parallel_transform_reduce`
- [ ] `parallel_deepcopy`
- [ ] `parallel_fill`

**Comment by acalloo** [comment]
I've pushed a first version on parallel_for_each. If it's ok for you, I'll finish the others before the end of this week.

**Comment by tpadioleau** [comment]
Looks fine to me, I just edited the previous message, in Kokkos doc I do not see `deep_copy` being overloading to take a string as a first parameter https://kokkos.org/kokkos-core-wiki/API/core/view/deep_copy.html?highlight=deep_copy

**Comment by jbigot** [comment]
@tpadioleau I think #361 closes this, right?
