### ISSUE TITLE
Check Kokkos_ENABLE_CUDA to activate the CUFFT_AVAIL flag

### ISSUE THREAD

**Issue by blegouix** [CExA-project/ddc#309]
Need to test Kokkos_ENABLE_CUDA too or we can have problem if cuFFT is loaded by another dependency

https://github.com/CExA-project/ddc/blame/7f53403295ecada6c584bb4885c5c5e7eaf6b3a8/CMakeLists.txt#L228

**Comment by tpadioleau** [comment]
Can you give the context in which you encountered a problem ?

**Comment by blegouix** [comment]
I added Torch (the AI framework) as dependency to Gysela (in its CMakeLists) and it had CUDAToolkit in dependency. But it does not relies on Kokkos. So, when I compiled without the Kokkos_ENABLE_CUDA flag it put cufft_AVAIL to ON whereas Kokkos_ENABLE_CUDA was OFF, so it tried to compile for example this:

`https://github.com/CExA-project/ddc/blob/7f53403295ecada6c584bb4885c5c5e7eaf6b3a8/include/ddc/kernels/fft.hpp#L444C31-L444C52`

**Comment by tpadioleau** [comment]
I see, thanks for the report. Indeed we should fix this. Can you also check that the option `DDC_BUILD_KERNELS_FFT` is `ON` ?

**Comment by blegouix** [comment]
Yes it is

**Comment by blegouix** [comment]
I propose a simple fix where I also check `Kokkos_ENABLE_CUDA=ON` in the condition which puts cufft_AVAIL to ON ? I have the setup to test it

**Comment by tpadioleau** [comment]
> Need to test Kokkos_ENABLE_CUDA too or we can have problem if cuFFT is loaded by another dependency
> 
> https://github.com/CExA-project/ddc/blame/7f53403295ecada6c584bb4885c5c5e7eaf6b3a8/CMakeLists.txt#L228

Not in this cmake line.

From the problem you mention, what happens if `CUDAToolkit_FOUND` is true, `Kokkos_ENABLE_CUDA` is `ON` but `DDC_BUILD_KERNELS_FFT` is `OFF` ?

**Comment by tpadioleau** [comment]
> I propose a simple fix where I also check `Kokkos_ENABLE_CUDA=ON` in the condition which puts cufft_AVAIL to ON ? I have the setup to test it

In your specific case, I agree it should be enough.

**Comment by blegouix** [comment]
I think `DDC_BUILD_KERNELS_FFT` just impacts the compilation of tests and example. If I compile DDC with `DDC_BUILD_KERNELS_FFT=OFF`, the `fft.hpp` file would not be included anywhere and then I would expect the compilation to run fine ? If I compile Gysela with `DDC_BUILD_KERNELS_FFT=OFF`, `fft.hpp` would be included by the Poisson solver and the same problem would happen. So I do not see what you want to test exactly ?

**Comment by blegouix** [comment]
![image](https://github.com/CExA-project/ddc/assets/22033714/dd3df2f8-f439-4e5a-8de8-e6c01482ef4f)
