### ISSUE TITLE
Ginkgo OMP problem

### ISSUE THREAD

**Issue by blegouix** [CExA-project/ddc#332]
Yann and me observed numerical issues in Gysela with OMP, even with OMP_NUM_THREADS=1.

#319 imputes the issue to Ginkgo with OMP executor.

I reproduce the issue by replacing:

`std::size_t constexpr ncells = 100;`

 with:
 
 `std::size_t constexpr ncells = 32;`

in `tests/splines/non_periodic_spline_builder.cpp`

(Note: there is no problem with `ncells = 10` too, which is the setup for the batched tests.)

Then the `splines_tests_DEGREE_X_3_BSPLINES_TYPE_UNIFORM_EVALUATOR_POLYNOMIAL_` tests will fail with error sometimes `> 1e-10`.

Doing the same in the #319 branch leads to all tests passing, with error usually around `1e-16`.

**Comment by blegouix** [comment]
Related branch:
https://github.com/CExA-project/ddc/tree/ginkgo-omp-debug

**Comment by tpadioleau** [comment]
Can you do a test without the preconditioner ? It was not clear it was helpful and it could help determining whether the problem comes from the solver or the preconditioner.

**Comment by blegouix** [comment]
You are right it is the preconditionner. Using `1u` (diagonal Jacobi) is enough to remove the problem.

**Comment by tpadioleau** [comment]
see https://github.com/ginkgo-project/ginkgo/issues/1563

**Comment by tpadioleau** [comment]
Could we consider switching to the GMRES solver in the meantime ?
