### ISSUE TITLE
Simplify Matrix API

### ISSUE THREAD

**Issue by blegouix** [CExA-project/ddc#336]
@EmilyBourne  proposes to simplify the Matrix API with an intermediate `MatrixLapack` class and  specialized `solve_inplace` for `MatrixSparse` and `MatrixLapack`.

`solve_inplace_method` would be removed or defined independently in `MatrixLapack` and `MatrixSparse`, but won't be a virtual function of `Matrix` anymore

**Comment by blegouix** [comment]
I wait #329 to be merged

**Comment by blegouix** [comment]
Duplicate with #425

**Comment by EmilyBourne** [comment]
I am not sure that this is a duplicate. Issues are for defining work to be done while discussions are about finding the right approach so an issue can be described. That said there is definitely a large overlap. I think we should probably edit and re-open this issue once a conclusion has been reached about the right interface to use
