### ISSUE TITLE
Identify the tasks to transfer linear algebra used in DDC splines to kokkos kernel

### ISSUE THREAD

**Issue by jbigot** [CExA-project/ddc#393]

**Comment by cedricchevalier19** [comment]
Meeting 5/13.

**Comment by blegouix** [comment]
Should I join ? Give me the time of the meeting if so

**Comment by yasahi-hpc** [comment]
https://github.com/kokkos/kokkos-kernels/pull/2202

**Comment by tpadioleau** [comment]
General dense
--------------
LAPACKE_dgetrs
LAPACKE_dgetrf

General banded
--------------
LAPACKE_dgbtrs
LAPACKE_dgbtrf

PDS banded
--------------
LAPACKE_dpbtrs
LAPACKE_dpbtrf

PDS tri-diag
--------------
LAPACKE_dpttrs
LAPACKE_dpttrf

**Comment by yasahi-hpc** [comment]
I have made a small investigation.

| Function | `dgetrs`   | `dgbtrs` | `dpbtrs` | `dpttrs` |
| -------- | -------- | ------- | ------- | ------- |
| Brief | general N-by-N matrix solver. A is factorized by `dgetrf` | general band matrix solver. A is factorized by `dgbtrf` | symmetric positive definite band matrix solver. A is factorized by `dpbtrf` | tridiagonal system solver. A is factorized by `dpttrf` |
| Dependency | `dlaswp`, `dtrsm` | `dgemv`, `dger`, `dswap`, `dtbsv` | `dtbsv` | `dptts2` |
| In Kokkos kernels | - | - | - | - |

These functions depend on following subroutines.

| Subroutines | `dlaswp`   | `dtrsm` | `dgemv` | `dger` | `dswap` | `dtbsv` | `dptts2` | `dscal` |
| -------- | -------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- |
| Brief | performs series of row interchanges on the matrix A | solves one of the matrix equations `op( A )*X = alpha*B`, or `X*op( A ) = alpha*B` | performs one of the matrix-vector operations `y := alpha*A*x + beta*y`, or   `y := alpha*A**T*x + beta*y` | performs the rank 1 operation `A := alpha*x*y**T + A` | interchanges two vectors | solves one of the systems of equations `A*x = b, or A**T*x = b` | solves a tridiagonal system of the form `A * X = B` using the `L*D*L'` factorization of A computed by dpttrf | scales a vector by a constant |
| Serial | - | x | x | - | | x | - | - |
| Team | - | x | x | - | - | - | - |  - |
| Team Vector | - | x | - | - | - | - | - |  - |
| Note | | |  | blas implementation available | | [ In review](https://github.com/kokkos/kokkos-kernels/pull/2202)  | Depends on `dscal` | blas implementation available |

**Comment by yasahi-hpc** [comment]
Implement batched serial pttrs [\#2277](https://github.com/kokkos/kokkos-kernels/pull/2277): In review
Implement batched serial pttrf [\#2256](https://github.com/kokkos/kokkos-kernels/pull/2256): merged
Add batched serial tbsv [\#2202](https://github.com/kokkos/kokkos-kernels/pull/2202): merged

**Comment by jbigot** [comment]
Great news!
