### ISSUE TITLE
Improve DDC Documentation

### ISSUE THREAD

**Issue by jbigot** [CExA-project/ddc#394]
When newcomers arrive in DDC, they have a hard-time grasping the concepts of DDC. We should provide some doc to help them:
our personae are:
* Alice

- [x] Baptiste has documented the splines (to be reviewed)
- [x] Restore clang-assisted parsing doxygen
- [x] improve ergonomic of the website
- [x] documentation of the concepts

**Comment by thierryantoun** [comment]
+ Write and comment a code that solves the heat equation using uniform discretization in space and time. [PR#410](https://github.com/CExA-project/ddc/pull/410)
