### ISSUE TITLE
Boundary conditions in spline_builder_2d.hpp

### ISSUE THREAD

**Issue by Paulinemoi** [CExA-project/ddc#402]
It seems there is mix between the boundary conditions on the first dimension and the second dimension. 
In spline_builder_2d.hpp, at lines 
https://github.com/CExA-project/ddc/blob/d652df884e1a53c9409905ebb2712530bb6f0c67/include/ddc/kernels/splines/spline_builder_2d.hpp#L382
and https://github.com/CExA-project/ddc/blob/d652df884e1a53c9409905ebb2712530bb6f0c67/include/ddc/kernels/splines/spline_builder_2d.hpp#L406
I think it should be `BcXmin2` and `BcXmax2` instead of `BcXmin1` and `BcXmax1` . 
In the case of Hermite boundary conditions on the two dimensions, it doesnt seem to affect it. But when the 2D basis has Hermite boundary conditions for one dimension and periodic boundary conditions for the second dimension, we have a error at the compilation.

**Comment by blegouix** [comment]
Yes I think you are right!
