### ISSUE TITLE
Tests missing for `BSplines.integrals`

### ISSUE THREAD

**Issue by EmilyBourne** [CExA-project/ddc#418]
The `BSplines.integrals` functions are not tested. This should be added ASAP. This is especially important as the handling of the `eval_basis` function in the uniform case is different to what is done elsewhere and is likely to be accidentally lost during refactoring

**Comment by blegouix** [comment]
This is tested through splines integrals right ?

**Comment by EmilyBourne** [comment]
Ah you are right. Sorry
