### ISSUE TITLE
Spline basis depend on the number of points

### ISSUE THREAD

**Issue by jbigot** [CExA-project/ddc#46]
See https://gitlab.maisondelasimulation.fr/gysela-developpers/voicexx/-/issues/40

We currently identify spline basis `BSplines` by a tag that is derived from the "real"/points discrete domain.

A spline basis does in fact depend on the domain rather than the dimension. We should see how we want to take that into account.

**Comment by tpadioleau** [comment]
Is it still an issue ?

**Comment by EmilyBourne** [comment]
> Is it still an issue ?

I don't think so. I think this has been fixed by the fact that splines now need to be defined as sub-classes

**Comment by tpadioleau** [comment]
Closing, feel free to reopen if it was not solved.
