### ISSUE TITLE
Optimize SplineEvaluator

### ISSUE THREAD

**Issue by blegouix** [CExA-project/ddc#499]
At https://github.com/CExA-project/ddc/blob/9f9292d837f5b4d8ebee76b2f7c5e0e04eaa5176/include/ddc/kernels/splines/spline_evaluator.hpp#L163 , replacing:

```
ddc::parallel_for_each(
                exec_space(),
                batch_domain,
                KOKKOS_CLASS_LAMBDA(typename batch_domain_type::discrete_element_type const j) {
                    const auto spline_eval_1D = spline_eval[j];
                    const auto coords_eval_1D = coords_eval[j];
                    const auto spline_coef_1D = spline_coef[j];
                    for (auto const i : evaluation_domain) {
                        spline_eval_1D(i) = eval(coords_eval_1D(i), spline_coef_1D);
                    }
                });
```

With:

```
ddc::parallel_for_each(
                exec_space(),
                spline_eval.domain(),
                KOKKOS_CLASS_LAMBDA(typename batched_evaluation_domain_type::discrete_element_type const e) {
                   typename evaluation_domain_type::discrete_element_type const i(e);
                   typename batch_domain_type::discrete_element_type const j(e);

                    spline_eval(i, j) = eval(coords_eval(i, j), spline_coef[j]);
                });
```

Makes the performance reduce from`1.59us` to `0.56us` (for a benchmark nx=1000, ny=100000).

The optimal solution may require hierarchical parallelism in ddc (#396) though and maybe transposition of `spline_coef` to make spline_coef[j] contiguous.

@tpadioleau should I address this ?

**Comment by tpadioleau** [comment]
Do you have a profiling of a spline interpolation on GPU ?

**Comment by blegouix** [comment]
Yeaah, that's milliseconds sorry

**Comment by blegouix** [comment]
Anyway, in fact there is another problem with this table, it is for ny=10000, not 100000. And I realize the patch is propose is actually slower with ny=100000. So I close the issue.
