### ISSUE TITLE
Likely wrong type

### ISSUE THREAD

**Issue by tpadioleau** [CExA-project/ddc#504]
https://github.com/CExA-project/ddc/blob/d6e6b58d3e33e7ff687b026c2e6b45bf0b495bb3/examples/non_uniform_heat_equation.cpp#L20

@thierryantoun did you really mean `int` or `double` for the bounds parameters of 
`generate_random_vector` ?

**Comment by thierryantoun** [comment]
As this function was only meant for this example, I put it as 'int' but in general it would be a 'double' I guess. Do you want me to change it ?

**Comment by tpadioleau** [comment]
Yes please do. The parameters that are given are of type `double`, we cannot implicitly round the values.
