### ISSUE TITLE
Labelized parallel_for_each with unspecified execution space does not work 

### ISSUE THREAD

**Issue by blegouix** [CExA-project/ddc#512]
This function:

https://github.com/CExA-project/ddc/blob/9e6ea8f49caf7b981ce73da5faaaea9f16264116/include/ddc/parallel_for_each.hpp#L188

Cannot be called because it is in conflict with the previous one. Maybe just interchanging the two may solve the problem ? Or Sfinae I guess

**Comment by tpadioleau** [comment]
Thanks, indeed SFINAE seems the way to go
