### ISSUE TITLE
Reduce memory footprint in the benchmark

### ISSUE THREAD

**Issue by tpadioleau** [CExA-project/ddc#528]
In the benchmark

https://github.com/CExA-project/ddc/blob/b9807014ea78e103378f246dcef917a964b1ad38/benchmarks/splines.cpp#L142

we allocate 2D coordinates, only a single coordinate is necessary. I think we should use a 1D coordinate to reduce the memory footprint and have better memory accesses.

**Comment by tpadioleau** [comment]
cc @blegouix

**Comment by blegouix** [comment]
"have better memory accesses" isn't it a reason to not do it ? We want to be the closest possible to real use-case no?

I would prefer to deduce the footprint of feet_coords in the computed value "gpu_mem_occupancy"

**Comment by tpadioleau** [comment]
I was not aware we were storing multi-dimensional coordinates in Gysela

**Comment by blegouix** [comment]
Ah, no sorry, you are correct
