### ISSUE TITLE
Missing error and documentation for Space template parameter of `create_mirror_view_and_copy`

### ISSUE THREAD

**Issue by EmilyBourne** [CExA-project/ddc#549]
The function `create_mirror_view_and_copy` has a template parameter called `Space`:
https://github.com/CExA-project/ddc/blob/2e705cb683681e5889dd40f68707c4c089f9e5fc/include/ddc/create_mirror.hpp#L100-L101

The generic name makes it difficult to tell if the function takes an `ExecSpace` or a `MemSpace`. There is no documentation to clarify. Digging through the call stack we see that eventually `ddc::parallel_deepcopy` is called. This function takes an `ExecSpace`:
https://github.com/CExA-project/ddc/blob/2e705cb683681e5889dd40f68707c4c089f9e5fc/include/ddc/parallel_deepcopy.hpp#L39-L40
Passing a `MemSpace` instead may be a common error as:
- The user is requesting a Chunk on a given memory space. The execution space of the potential copy is a secondary consideration and therefore may not be immediately considered
- The equivalent Kokkos function `kokkos::create_mirror_view_and_copy` takes a `MemSpace
    https://github.com/kokkos/kokkos/blob/8e682582fd8302008ce5e422377e4ef2d730c23b/core/src/Kokkos_CopyViews.hpp#L3719-L3722`
    E.g:
    https://github.com/CExA-project/ddc/blob/2e705cb683681e5889dd40f68707c4c089f9e5fc/include/ddc/non_uniform_point_sampling.hpp#L101

The function should be documented and a static assert should be added to ensure that the correct kind of space is passed to the function.

_Originally seen in https://gitlab.maisondelasimulation.fr/gysela-developpers/gyselalibxx/-/merge_requests/526#note_59376_

**Comment by tpadioleau** [comment]
Yep, closely related to #542
