### ISSUE TITLE
Quadrature coefficients on device lead to Segfault

### ISSUE THREAD

**Issue by Geoflow** [CExA-project/ddc#598]
Hello,
During an atempt to get device allocated quadrature coefficients from SplineBuilder, we discovered an issue related to the following line. 
Code which produced the segfault:
```cpp
ddc::Chunk<
            double,
            ddc::DiscreteDomain<Grid>,
            ddc::KokkosAllocator<double, typename SplineBuilder::memory_space>> // Kokkos::DefaultExecutionSpace()
            quadrature_coefficients;
std::tie(std::ignore, quadrature_coefficients, std::ignore) = builder.quadrature_coefficients();
```
loop which is responsible:
https://github.com/CExA-project/ddc/blob/93b822f713fa326432aec9376c347a7f5b63df59/include/ddc/kernels/splines/bsplines_uniform.hpp#L616-L618

Abdelhadi

**Comment by tpadioleau** [comment]
Thank you for the report. Indeed it cannot work as the function `integrals` expects data accessible from where it is called.

I also notice that the tests calling the function run always on the host. I think it also needs to be updated.
