### ISSUE TITLE
Create a configuration file containing preprocessor definitions

### ISSUE THREAD

**Issue by tpadioleau** [CExA-project/ddc#666]
Following #665, instead of propagating definitions with `target_compile_definitions` I would prefer that we generate a `ddc_config.hpp` with these definitions. It would be cleaner for projects relying on DDC.

**Comment by jbigot** [comment]
Agreed, no reason I see for that

**Comment by tpadioleau** [comment]
Only some of our examples use `DDC_BUILD_PDI_WRAPPER` but we can work around
