### ISSUE TITLE
Add ChunkSpan user-defined CTAD taking a Chunk

### ISSUE THREAD

**Issue by blegouix** [CExA-project/ddc#703]
```
template <class ElementType, class SupportType, class Allocator>
ChunkSpan(Chunk<ElementType, SupportType, Allocator>) -> ChunkSpan<ElementType, SupportType, Kokkos::layout_right, typename Allocator::memory_space>;
```

Would make:

```
ddc::ChunkSpan some_span(some_alloc);
```

An alternative to:

```
ddc::ChunkSpan some_span = some_alloc.span_view();
```

(it does not look very useful but I am working with a class derived from ChunkSpan, so I cannot rely on `span_view()` to get an instance of this class, and i found implementing this deduction guide convenient for my class)

**Comment by tpadioleau** [comment]
This seems totally reasonable
